FlowRouter.route('/',{
	name:'elias',
	action(){
		BlazeLayout.render('nav',{main:'form'});
	}
});
FlowRouter.route('/about',{
	name:'About',
	action(){
		BlazeLayout.render('about');
	}
});
FlowRouter.route('/contact',{
	name:'About',
	action(){
		BlazeLayout.render('contact');
	}
});
FlowRouter.route('/profile',{
	name:'Profile',
	subscriptions:function(params, queryParams)
	{
		this.register("loadMuro",Meteor.subscribe("getArticles",Meteor.userId()));
	},
	action(){
		BlazeLayout.render('profile');
	}
});