FlowRouter.route('/',{
	name:'elias',
	action(){
		BlazeLayout.render('nav',{main:'form'});
	}
});
FlowRouter.route('/about',{
	name:'About',
	action(){
		BlazeLayout.render('about');
	}
});
FlowRouter.route('/contact',{
	name:'About',
	action(){
		BlazeLayout.render('contact');
	}
});
FlowRouter.route('/profile',{
	name:'Profile',
	action(){
		BlazeLayout.render('profile');
	}
});